apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice-kit-config
data:
  redis-addr: redis-service:6379
  registry-address: http://microservice-kit-consul:8500
  storage-endpoint: rustfs-service:9000
