import type { ReactNode } from 'react';
import type { ComponentType } from 'react';
import {
  ApiApp,
  Apps,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bolt,
  Book,
  Bug,
  Bulb,
  Check,
  ChevronDown,
  ChevronUp,
  CircleCheck,
  Clock,
  Cloud,
  Code,
  Copy,
  Database,
  DeviceDesktop,
  DeviceDesktopAnalytics,
  DotsVertical,
  Download,
  Eye,
  File,
  Folder,
  Hierarchy,
  Home,
  Key,
  LayoutDashboard,
  LayoutSidebarLeftCollapse,
  LayoutSidebarLeftExpand,
  Link,
  List,
  Lock,
  Login,
  Logout,
  Moon,
  Pencil,
  Pin,
  PinFilled,
  Plus,
  Refresh,
  Rocket,
  Search,
  Server,
  Settings,
  Shield,
  Sun,
  Tools,
  Trash,
  Upload,
  User,
  UserPlus,
  Users,
} from '@appica/icons-react';

export {
  ArrowDown as ArrowDownOutlined,
  ArrowLeft as ArrowLeftOutlined,
  ArrowRight as ArrowRightOutlined,
  ArrowUp as ArrowUpOutlined,
  LayoutDashboard as DashboardOutlined,
  Bulb as BulbOutlined,
  Check as CheckOutlined,
  CircleCheck as CheckCircleOutlined,
  Copy as CopyOutlined,
  ChevronDown as DownOutlined,
  ChevronUp as UpOutlined,
  Clock as FieldTimeOutlined,
  LayoutSidebarLeftCollapse as MenuFoldOutlined,
  LayoutSidebarLeftExpand as MenuUnfoldOutlined,
  Logout as LogoutOutlined,
  DotsVertical as MoreOutlined,
  Moon as MoonOutlined,
  Pencil as EditOutlined,
  PinFilled as PushpinFilled,
  Pin as PushpinOutlined,
  Plus as PlusOutlined,
  Search as SearchOutlined,
  Sun as SunOutlined,
  Trash as DeleteOutlined,
  User as UserOutlined,
  UserPlus as UserSwitchOutlined,
  Users as TeamOutlined,
};

const iconNameMap: Record<string, ComponentType> = {
  dashboard: LayoutDashboard,
  home: Home,
  setting: Settings,
  system: Settings,
  user: User,
  peoples: Users,
  team: Users,
  cloud: Cloud,
  file: File,
  upload: Upload,
  database: Database,
  dict: Book,
  monitor: DeviceDesktopAnalytics,
  login: Login,
  logininfor: Login,
  form: File,
  server: Server,
  tree: Hierarchy,
  'tree-table': Hierarchy,
  search: Search,
  reload: Refresh,
  download: Download,
  delete: Trash,
  plus: Plus,
  eye: Eye,
  lock: Lock,
  key: Key,
  api: ApiApp,
  code: Code,
  bug: Bug,
  rocket: Rocket,
  control: Settings,
  tool: Tools,
  book: Book,
  bars: List,
  safety: Shield,
  folder: Folder,
};

export const iconOptions = Object.keys(iconNameMap).map((key) => ({
  label: key,
  value: key,
}));

export function getMenuIconNode(iconName?: string): ReactNode {
  const IconComponent = iconName ? iconNameMap[iconName] : undefined;
  return IconComponent ? <IconComponent /> : <Apps />;
}

export {
  ApiApp as ApiOutlined,
  Apps as AppstoreOutlined,
  Bolt as ThunderboltOutlined,
  Book as BookOutlined,
  Bug as BugOutlined,
  Cloud as CloudOutlined,
  Code as CodeOutlined,
  Database as DatabaseOutlined,
  DeviceDesktop as DesktopOutlined,
  DeviceDesktopAnalytics as MonitorOutlined,
  Download as DownloadOutlined,
  Eye as EyeOutlined,
  File as FileOutlined,
  Folder as FolderOutlined,
  Hierarchy as ApartmentOutlined,
  Home as HomeOutlined,
  Key as KeyOutlined,
  Link as LinkOutlined,
  List as BarsOutlined,
  Lock as LockOutlined,
  Login as LoginOutlined,
  Refresh as ReloadOutlined,
  Rocket as RocketOutlined,
  Server as CloudServerOutlined,
  Settings as ControlOutlined,
  Settings as SettingOutlined,
  Shield as SafetyOutlined,
  Tools as ToolOutlined,
  Upload as UploadOutlined,
};
